# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\x0f\x63ontext_monitor\"\x0e\n\x0c\x45mptyRequest\"\x1f\n\x0fVariableRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"L\n\x10VariableResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\r\n\x05\x66ound\x18\x04 \x01(\x08\"-\n\x0eVariableUpdate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\rVariablesList\x12\r\n\x05names\x18\x01 \x03(\t2\x85\x02\n\x0eMonitorService\x12R\n\x0bGetVariable\x12 .context_monitor.VariableRequest\x1a!.context_monitor.VariableResponse\x12O\n\x0bSetVariable\x12\x1f.context_monitor.VariableUpdate\x1a\x1f.context_monitor.StatusResponse\x12N\n\rListVariables\x12\x1d.context_monitor.EmptyRequest\x1a\x1e.context_monitor.VariablesListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=34
  _globals['_EMPTYREQUEST']._serialized_end=48
  _globals['_VARIABLEREQUEST']._serialized_start=50
  _globals['_VARIABLEREQUEST']._serialized_end=81
  _globals['_VARIABLERESPONSE']._serialized_start=83
  _globals['_VARIABLERESPONSE']._serialized_end=159
  _globals['_VARIABLEUPDATE']._serialized_start=161
  _globals['_VARIABLEUPDATE']._serialized_end=206
  _globals['_STATUSRESPONSE']._serialized_start=208
  _globals['_STATUSRESPONSE']._serialized_end=258
  _globals['_VARIABLESLIST']._serialized_start=260
  _globals['_VARIABLESLIST']._serialized_end=290
  _globals['_MONITORSERVICE']._serialized_start=293
  _globals['_MONITORSERVICE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
