// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: monitor.proto
#ifndef GRPC_monitor_2eproto__INCLUDED
#define GRPC_monitor_2eproto__INCLUDED

#include "monitor.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace context_monitor {

class MonitorService final {
 public:
  static constexpr char const* service_full_name() {
    return "context_monitor.MonitorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 获取变量值
    virtual ::grpc::Status GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::context_monitor::VariableResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariableResponse>> AsyncGetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariableResponse>>(AsyncGetVariableRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariableResponse>> PrepareAsyncGetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariableResponse>>(PrepareAsyncGetVariableRaw(context, request, cq));
    }
    // 设置变量值
    virtual ::grpc::Status SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::context_monitor::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::StatusResponse>> AsyncSetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::StatusResponse>>(AsyncSetVariableRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::StatusResponse>> PrepareAsyncSetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::StatusResponse>>(PrepareAsyncSetVariableRaw(context, request, cq));
    }
    // 列出所有变量
    virtual ::grpc::Status ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::context_monitor::VariablesList* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariablesList>> AsyncListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariablesList>>(AsyncListVariablesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariablesList>> PrepareAsyncListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariablesList>>(PrepareAsyncListVariablesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 获取变量值
      virtual void GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 设置变量值
      virtual void SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 列出所有变量
      virtual void ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariableResponse>* AsyncGetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariableResponse>* PrepareAsyncGetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::StatusResponse>* AsyncSetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::StatusResponse>* PrepareAsyncSetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariablesList>* AsyncListVariablesRaw(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::context_monitor::VariablesList>* PrepareAsyncListVariablesRaw(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::context_monitor::VariableResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::VariableResponse>> AsyncGetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::VariableResponse>>(AsyncGetVariableRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::VariableResponse>> PrepareAsyncGetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::VariableResponse>>(PrepareAsyncGetVariableRaw(context, request, cq));
    }
    ::grpc::Status SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::context_monitor::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::StatusResponse>> AsyncSetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::StatusResponse>>(AsyncSetVariableRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::StatusResponse>> PrepareAsyncSetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::StatusResponse>>(PrepareAsyncSetVariableRaw(context, request, cq));
    }
    ::grpc::Status ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::context_monitor::VariablesList* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::VariablesList>> AsyncListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::VariablesList>>(AsyncListVariablesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::VariablesList>> PrepareAsyncListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::context_monitor::VariablesList>>(PrepareAsyncListVariablesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response, std::function<void(::grpc::Status)>) override;
      void GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response, std::function<void(::grpc::Status)>) override;
      void ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::context_monitor::VariableResponse>* AsyncGetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::context_monitor::VariableResponse>* PrepareAsyncGetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::context_monitor::StatusResponse>* AsyncSetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::context_monitor::StatusResponse>* PrepareAsyncSetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::context_monitor::VariablesList>* AsyncListVariablesRaw(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::context_monitor::VariablesList>* PrepareAsyncListVariablesRaw(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetVariable_;
    const ::grpc::internal::RpcMethod rpcmethod_SetVariable_;
    const ::grpc::internal::RpcMethod rpcmethod_ListVariables_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 获取变量值
    virtual ::grpc::Status GetVariable(::grpc::ServerContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response);
    // 设置变量值
    virtual ::grpc::Status SetVariable(::grpc::ServerContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response);
    // 列出所有变量
    virtual ::grpc::Status ListVariables(::grpc::ServerContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetVariable() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableRequest* /*request*/, ::context_monitor::VariableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVariable(::grpc::ServerContext* context, ::context_monitor::VariableRequest* request, ::grpc::ServerAsyncResponseWriter< ::context_monitor::VariableResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetVariable() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableUpdate* /*request*/, ::context_monitor::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetVariable(::grpc::ServerContext* context, ::context_monitor::VariableUpdate* request, ::grpc::ServerAsyncResponseWriter< ::context_monitor::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListVariables() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ListVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListVariables(::grpc::ServerContext* /*context*/, const ::context_monitor::EmptyRequest* /*request*/, ::context_monitor::VariablesList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListVariables(::grpc::ServerContext* context, ::context_monitor::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::context_monitor::VariablesList>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetVariable<WithAsyncMethod_SetVariable<WithAsyncMethod_ListVariables<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetVariable() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::context_monitor::VariableRequest, ::context_monitor::VariableResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response) { return this->GetVariable(context, request, response); }));}
    void SetMessageAllocatorFor_GetVariable(
        ::grpc::MessageAllocator< ::context_monitor::VariableRequest, ::context_monitor::VariableResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::context_monitor::VariableRequest, ::context_monitor::VariableResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableRequest* /*request*/, ::context_monitor::VariableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVariable(
      ::grpc::CallbackServerContext* /*context*/, const ::context_monitor::VariableRequest* /*request*/, ::context_monitor::VariableResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetVariable() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::context_monitor::VariableUpdate, ::context_monitor::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response) { return this->SetVariable(context, request, response); }));}
    void SetMessageAllocatorFor_SetVariable(
        ::grpc::MessageAllocator< ::context_monitor::VariableUpdate, ::context_monitor::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::context_monitor::VariableUpdate, ::context_monitor::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableUpdate* /*request*/, ::context_monitor::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetVariable(
      ::grpc::CallbackServerContext* /*context*/, const ::context_monitor::VariableUpdate* /*request*/, ::context_monitor::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListVariables() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::context_monitor::EmptyRequest, ::context_monitor::VariablesList>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response) { return this->ListVariables(context, request, response); }));}
    void SetMessageAllocatorFor_ListVariables(
        ::grpc::MessageAllocator< ::context_monitor::EmptyRequest, ::context_monitor::VariablesList>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::context_monitor::EmptyRequest, ::context_monitor::VariablesList>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListVariables(::grpc::ServerContext* /*context*/, const ::context_monitor::EmptyRequest* /*request*/, ::context_monitor::VariablesList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListVariables(
      ::grpc::CallbackServerContext* /*context*/, const ::context_monitor::EmptyRequest* /*request*/, ::context_monitor::VariablesList* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetVariable<WithCallbackMethod_SetVariable<WithCallbackMethod_ListVariables<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetVariable() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableRequest* /*request*/, ::context_monitor::VariableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetVariable() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableUpdate* /*request*/, ::context_monitor::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListVariables() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ListVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListVariables(::grpc::ServerContext* /*context*/, const ::context_monitor::EmptyRequest* /*request*/, ::context_monitor::VariablesList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetVariable() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableRequest* /*request*/, ::context_monitor::VariableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVariable(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetVariable() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableUpdate* /*request*/, ::context_monitor::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetVariable(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListVariables() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ListVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListVariables(::grpc::ServerContext* /*context*/, const ::context_monitor::EmptyRequest* /*request*/, ::context_monitor::VariablesList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListVariables(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetVariable() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetVariable(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableRequest* /*request*/, ::context_monitor::VariableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVariable(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetVariable() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetVariable(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableUpdate* /*request*/, ::context_monitor::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetVariable(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListVariables() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListVariables(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListVariables(::grpc::ServerContext* /*context*/, const ::context_monitor::EmptyRequest* /*request*/, ::context_monitor::VariablesList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListVariables(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetVariable() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::context_monitor::VariableRequest, ::context_monitor::VariableResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::context_monitor::VariableRequest, ::context_monitor::VariableResponse>* streamer) {
                       return this->StreamedGetVariable(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableRequest* /*request*/, ::context_monitor::VariableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetVariable(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::context_monitor::VariableRequest,::context_monitor::VariableResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetVariable() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::context_monitor::VariableUpdate, ::context_monitor::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::context_monitor::VariableUpdate, ::context_monitor::StatusResponse>* streamer) {
                       return this->StreamedSetVariable(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetVariable(::grpc::ServerContext* /*context*/, const ::context_monitor::VariableUpdate* /*request*/, ::context_monitor::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetVariable(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::context_monitor::VariableUpdate,::context_monitor::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListVariables() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::context_monitor::EmptyRequest, ::context_monitor::VariablesList>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::context_monitor::EmptyRequest, ::context_monitor::VariablesList>* streamer) {
                       return this->StreamedListVariables(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListVariables(::grpc::ServerContext* /*context*/, const ::context_monitor::EmptyRequest* /*request*/, ::context_monitor::VariablesList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListVariables(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::context_monitor::EmptyRequest,::context_monitor::VariablesList>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetVariable<WithStreamedUnaryMethod_SetVariable<WithStreamedUnaryMethod_ListVariables<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetVariable<WithStreamedUnaryMethod_SetVariable<WithStreamedUnaryMethod_ListVariables<Service > > > StreamedService;
};

}  // namespace context_monitor


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_monitor_2eproto__INCLUDED
