// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: monitor.proto

#include "monitor.pb.h"
#include "monitor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace context_monitor {

static const char* MonitorService_method_names[] = {
  "/context_monitor.MonitorService/GetVariable",
  "/context_monitor.MonitorService/SetVariable",
  "/context_monitor.MonitorService/ListVariables",
};

std::unique_ptr< MonitorService::Stub> MonitorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MonitorService::Stub> stub(new MonitorService::Stub(channel, options));
  return stub;
}

MonitorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetVariable_(MonitorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetVariable_(MonitorService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListVariables_(MonitorService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MonitorService::Stub::GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::context_monitor::VariableResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::context_monitor::VariableRequest, ::context_monitor::VariableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVariable_, context, request, response);
}

void MonitorService::Stub::async::GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::context_monitor::VariableRequest, ::context_monitor::VariableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVariable_, context, request, response, std::move(f));
}

void MonitorService::Stub::async::GetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVariable_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::context_monitor::VariableResponse>* MonitorService::Stub::PrepareAsyncGetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::context_monitor::VariableResponse, ::context_monitor::VariableRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVariable_, context, request);
}

::grpc::ClientAsyncResponseReader< ::context_monitor::VariableResponse>* MonitorService::Stub::AsyncGetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVariableRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MonitorService::Stub::SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::context_monitor::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::context_monitor::VariableUpdate, ::context_monitor::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetVariable_, context, request, response);
}

void MonitorService::Stub::async::SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::context_monitor::VariableUpdate, ::context_monitor::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetVariable_, context, request, response, std::move(f));
}

void MonitorService::Stub::async::SetVariable(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetVariable_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::context_monitor::StatusResponse>* MonitorService::Stub::PrepareAsyncSetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::context_monitor::StatusResponse, ::context_monitor::VariableUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetVariable_, context, request);
}

::grpc::ClientAsyncResponseReader< ::context_monitor::StatusResponse>* MonitorService::Stub::AsyncSetVariableRaw(::grpc::ClientContext* context, const ::context_monitor::VariableUpdate& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetVariableRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MonitorService::Stub::ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::context_monitor::VariablesList* response) {
  return ::grpc::internal::BlockingUnaryCall< ::context_monitor::EmptyRequest, ::context_monitor::VariablesList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListVariables_, context, request, response);
}

void MonitorService::Stub::async::ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::context_monitor::EmptyRequest, ::context_monitor::VariablesList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListVariables_, context, request, response, std::move(f));
}

void MonitorService::Stub::async::ListVariables(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListVariables_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::context_monitor::VariablesList>* MonitorService::Stub::PrepareAsyncListVariablesRaw(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::context_monitor::VariablesList, ::context_monitor::EmptyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListVariables_, context, request);
}

::grpc::ClientAsyncResponseReader< ::context_monitor::VariablesList>* MonitorService::Stub::AsyncListVariablesRaw(::grpc::ClientContext* context, const ::context_monitor::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListVariablesRaw(context, request, cq);
  result->StartCall();
  return result;
}

MonitorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MonitorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MonitorService::Service, ::context_monitor::VariableRequest, ::context_monitor::VariableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MonitorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::context_monitor::VariableRequest* req,
             ::context_monitor::VariableResponse* resp) {
               return service->GetVariable(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MonitorService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MonitorService::Service, ::context_monitor::VariableUpdate, ::context_monitor::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MonitorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::context_monitor::VariableUpdate* req,
             ::context_monitor::StatusResponse* resp) {
               return service->SetVariable(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MonitorService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MonitorService::Service, ::context_monitor::EmptyRequest, ::context_monitor::VariablesList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MonitorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::context_monitor::EmptyRequest* req,
             ::context_monitor::VariablesList* resp) {
               return service->ListVariables(ctx, req, resp);
             }, this)));
}

MonitorService::Service::~Service() {
}

::grpc::Status MonitorService::Service::GetVariable(::grpc::ServerContext* context, const ::context_monitor::VariableRequest* request, ::context_monitor::VariableResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MonitorService::Service::SetVariable(::grpc::ServerContext* context, const ::context_monitor::VariableUpdate* request, ::context_monitor::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MonitorService::Service::ListVariables(::grpc::ServerContext* context, const ::context_monitor::EmptyRequest* request, ::context_monitor::VariablesList* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace context_monitor
#include <grpcpp/ports_undef.inc>

